spring:
  datasource:
    url: ${H2_URL:jdbc:h2:mem:appdb}
    username: ${H2_USERNAME:sa}
    password: ${H2_PASSWORD:password}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: ${H2_CONSOLE_PATH:/h2-console}

csv:
  initialization:
    filename: ${CSV_INITIALIZATION_FILE:specification/movielist.csv}
    separator: ${CSV_INITIALIZATION_SEPARATOR:;}